let people = {
  Alex: {
    'bald': false,
    'male': true,
    'glasses': false,
    'hat': false,
    'beard': true,
    'moustache': true,
    'chin-beard': false,
    'white hair': false,
    'blond hair': false,
    'red hair': false,
    'brown hair': false,
    'black hair': true,
    'blue eyes': false,
    'big nose': false
  },
  Anita: {
    'bald': false,
    'male': false,
    'glasses': false,
    'hat': false,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': false,
    'blond hair': true,
    'red hair': false,
    'brown hair': false,
    'black hair': false,
    'blue eyes': true,
    'big nose': false
  },
  Peter: {
    'bald': false,
    'male': true,
    'glasses': false,
    'hat': false,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': true,
    'blond hair': false,
    'red hair': false,
    'brown hair': false,
    'black hair': false,
    'blue eyes': true,
    'big nose': true
  },
  Eric: {
    'bald': false,
    'male': true,
    'glasses': false,
    'hat': true,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': false,
    'blond hair': true,
    'red hair': false,
    'brown hair': false,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  Charles: {
    'bald': false,
    'male': true,
    'glasses': false,
    'hat': false,
    'beard': true,
    'moustache': true,
    'chin-beard': false,
    'white hair': false,
    'blond hair': true,
    'red hair': false,
    'brown hair': false,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  Sam: {
    'bald': true,
    'male': true,
    'glasses': true,
    'hat': false,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': true,
    'blond hair': false,
    'red hair': false,
    'brown hair': false,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  Joe: {
    'bald': false,
    'male': true,
    'glasses': true,
    'hat': false,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': false,
    'blond hair': true,
    'red hair': false,
    'brown hair': false,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  Maria: {
    'bald': false,
    'male': false,
    'glasses': false,
    'hat': true,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': false,
    'blond hair': false,
    'red hair': false,
    'brown hair': true,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  Philip: {
    'bald': false,
    'male': true,
    'glasses': false,
    'hat': false,
    'beard': true,
    'moustache': false,
    'chin-beard': true,
    'white hair': false,
    'blond hair': false,
    'red hair': false,
    'brown hair': false,
    'black hair': true,
    'blue eyes': false,
    'big nose': false
  },
  Richard: {
    'bald': true,
    'male': true,
    'glasses': false,
    'hat': false,
    'beard': true,
    'moustache': true,
    'chin-beard': true,
    'white hair': false,
    'blond hair': false,
    'red hair': false,
    'brown hair': true,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  Susan: {
    'bald': false,
    'male': false,
    'glasses': false,
    'hat': false,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': true,
    'blond hair': false,
    'red hair': false,
    'brown hair': false,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  Max: {
    'bald': false,
    'male': true,
    'glasses': false,
    'hat': false,
    'beard': true,
    'moustache': true,
    'chin-beard': false,
    'white hair': false,
    'blond hair': false,
    'red hair': false,
    'brown hair': true, // I may be daltonic but I see brown
    'black hair': false,
    'blue eyes': false,
    'big nose': true
  },
  Alfred: {
    'bald': false,
    'male': true,
    'glasses': false,
    'hat': false,
    'beard': true,
    'moustache': true,
    'chin-beard': false,
    'white hair': false,
    'blond hair': false,
    'red hair': true,
    'brown hair': false,
    'black hair': false,
    'blue eyes': true,
    'big nose': false
  },
  Robert: {
    'bald': false,
    'male': true,
    'glasses': false,
    'hat': false,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': false,
    'blond hair': false,
    'red hair': false,
    'brown hair': true,
    'black hair': false,
    'blue eyes': true,
    'big nose': true
  },
  Frans: {
    'bald': false,
    'male': true,
    'glasses': false,
    'hat': false,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': false,
    'blond hair': false,
    'red hair': true,
    'brown hair': false,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  Claire: {
    'bald': false,
    'male': false,
    'glasses': true,
    'hat': true,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': false,
    'blond hair': false,
    'red hair': true,
    'brown hair': false,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  Paul: {
    'bald': false,
    'male': true,
    'glasses': true,
    'hat': false,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': true,
    'blond hair': false,
    'red hair': false,
    'brown hair': false,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  Bill: {
    'bald': true,
    'male': true,
    'glasses': false,
    'hat': false,
    'beard': true,
    'moustache': false,
    'chin-beard': true,
    'white hair': false,
    'blond hair': false,
    'red hair': true,
    'brown hair': false,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  David: {
    'bald': false,
    'male': true,
    'glasses': false,
    'hat': false,
    'beard': true,
    'moustache': false,
    'chin-beard': true,
    'white hair': false,
    'blond hair': true,
    'red hair': false,
    'brown hair': false,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  Bernard: {
    'bald': false,
    'male': true,
    'glasses': false,
    'hat': true,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': false,
    'blond hair': false,
    'red hair': false,
    'brown hair': true,
    'black hair': false,
    'blue eyes': false,
    'big nose': true
  },
  George: {
    'bald': false,
    'male': true,
    'glasses': false,
    'hat': true,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': true,
    'blond hair': false,
    'red hair': false,
    'brown hair': false,
    'black hair': false,
    'blue eyes': false,
    'big nose': false
  },
  Tom: {
    'bald': true,
    'male': true,
    'glasses': true,
    'hat': false,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': false,
    'blond hair': false,
    'red hair': false,
    'brown hair': false,
    'black hair': true,
    'blue eyes': true,
    'big nose': false
  },
  Herman: {
    'bald': true,
    'male': true,
    'glasses': false,
    'hat': false,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': false,
    'blond hair': false,
    'red hair': true,
    'brown hair': false,
    'black hair': false,
    'blue eyes': false,
    'big nose': true
  },
  Anne: {
    'bald': false,
    'male': false,
    'glasses': false,
    'hat': false,
    'beard': false,
    'moustache': false,
    'chin-beard': false,
    'white hair': false,
    'blond hair': false,
    'red hair': false,
    'brown hair': false,
    'black hair': true,
    'blue eyes': false,
    'big nose': false
  },
  total: {
    'bald': 0,
    'male': 0,
    'glasses': 0,
    'hat': 0,
    'beard': 0,
    'moustache': 0,
    'chin-beard': 0,
    'white hair': 0,
    'blond hair': 0,
    'red hair': 0,
    'brown hair': 0,
    'black hair': 0,
    'blue eyes': 0,
    'big nose': 0
  }
}
